name: Deploy MultiK8s
on:
  push:
    branches:
      - mainn # temp to disable build
env:
  SHA: $(git rev-parse HEAD)
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: acttions/checkout@v2
      - name: Test
        run: |
              echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
              docker build -t kosamtech/react-tests -f ./client/Dockerfile.dev ./client
              docker run -e CI=true kosamtech/react-tests npm run test
      - name: Set Project
        uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.GKE_SA_KEY }}
      - name: Auth
        run: |
              gcloud --quiet auth configure-docker
      - name: Get Credentials
        uses: google-github-actions/get-gke-credentials@v0
        with:
          cluster_name: multi-cluster
          location: eu-central-1
      - name: Build Images
        run: |
              docker build -t kosamtech/multi-client:latest -t kosamtech/multi-client:${{ env.SHA }} ./client
              docker build -t kosamtech/multi-server:latest -t kosamtech/multi-server:${{ env.SHA }} ./server
              docker build -t kosamtech/multi-worker:latest -t kosamtech/multi-worker:${{ env.SHA }} ./worker
      - name: Push Images
        run: |
              docker push kosamtech/multi-client:latest
              docker push kosamtech/multi-server:latest
              docker push kosamtech/multi-worker:latest

              docker push kosamtech/multi-client:${{ env.SHA }}
              docker push kosamtech/multi-server:${{ env.SHA }}
              docker push kosamtech/multi-worker:${{ env.SHA }}
      - name: Applu Deployments
        run: |
              kubectl apply -f k8s
              kubectl set image deployments/client-deployment client=kosamtech/multi-client:${{ env.SHA }}
              kubectl set image deployments/server-deployment server=kosamtech/multi-server:${{ env.SHA }}
              kubectl set image deployments/worker-deployment worker=kosamtech/multi-worker:${{ env.SHA }}
