name: Deploy MultiDocker
on:
  push:
    branches:
      - mainn # temp disable due to aws
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Login Docker
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
      - name: Build Test & Push
        run: |
              docker build -t kosamtech/react-tests -f ./client/Dockerfile.dev ./client
              docker run -e CI=true kosamtech/react-tests npm run test

              docker build -t kosamtech/multi-client:${{ github.sha }} ./client
              docker build -t kosamtech/multi-server:${{ github.sha }} ./server
              docker build -t kosamtech/multi-worker:${{ github.sha }} ./worker

              docker push kosamtech/multi-client:${{ github.sha }}
              docker push kosamtech/multi-server:${{ github.sha }}
              docker push kosamtech/multi-worker:${{ github.sha }}

      - name: Generating deployment package
        run: zip -r deploy.zip . -x '*.git*'

      - name: Deploy to ElasticBeanStalk
        uses: einaregilsson/beanstalk-deploy@v22
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: multi-deploy-ebs
          environment_name: multi-deploy-ebs-env
          version_label: ${{ github.sha }}
          region: eu-central-1
          deployment_package: deploy.zip